// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using silverkissen.Models;

namespace silverkissen.Migrations
{
    [DbContext(typeof(SilverkissenContext))]
    [Migration("20190622002538_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("silverkissen.DbModels.CatFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatId");

                    b.Property<int>("CatLitterId");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("CatLitterId");

                    b.ToTable("CatFamilies");
                });

            modelBuilder.Entity("silverkissen.DbModels.CatImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatId");

                    b.Property<int>("ImageId");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.HasIndex("ImageId");

                    b.ToTable("CatImages");
                });

            modelBuilder.Entity("silverkissen.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Breed");

                    b.Property<bool>("Chipped");

                    b.Property<string>("Color");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<bool>("Parent");

                    b.Property<bool>("Pedigree");

                    b.Property<bool>("SVERAK");

                    b.Property<string>("Sex");

                    b.Property<bool>("Vaccinated");

                    b.HasKey("Id");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("silverkissen.Models.CatLitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfKids");

                    b.Property<DateTime>("BirthDate");

                    b.Property<bool>("Chipped");

                    b.Property<string>("Notes");

                    b.Property<bool>("Pedigree");

                    b.Property<string>("PedigreeName");

                    b.Property<DateTime>("ReadyDate");

                    b.Property<bool>("SVERAK");

                    b.Property<string>("Status");

                    b.Property<bool>("Vaccinated");

                    b.HasKey("Id");

                    b.ToTable("CatLitters");
                });

            modelBuilder.Entity("silverkissen.Models.CatLitterImages", b =>
                {
                    b.Property<int>("CatLitterId");

                    b.Property<int>("ImageId");

                    b.Property<int>("Id");

                    b.HasKey("CatLitterId", "ImageId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("CatLitterImages");
                });

            modelBuilder.Entity("silverkissen.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Filename");

                    b.Property<string>("Filetype");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("silverkissen.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("silverkissen.DbModels.CatFamily", b =>
                {
                    b.HasOne("silverkissen.Models.Cat")
                        .WithMany("CatFamily")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("silverkissen.Models.CatLitter")
                        .WithMany("CatFamily")
                        .HasForeignKey("CatLitterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("silverkissen.DbModels.CatImages", b =>
                {
                    b.HasOne("silverkissen.Models.Cat")
                        .WithMany("CatImages")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("silverkissen.Models.Image")
                        .WithMany("CatImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("silverkissen.Models.CatLitterImages", b =>
                {
                    b.HasOne("silverkissen.Models.CatLitter")
                        .WithMany("LitterImages")
                        .HasForeignKey("CatLitterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("silverkissen.Models.Image")
                        .WithMany("CatLitter")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
